In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1+cu121


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get Python number from a tensor
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0], matrix[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [15]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7558, 0.0631, 0.8523, 0.7911],
        [0.8893, 0.3383, 0.8198, 0.5969],
        [0.8848, 0.1351, 0.0726, 0.2416]])

In [16]:
random_tensor.ndim

2

In [17]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

In [22]:
# Range of tensors and tensors-like
one_to_ten = torch.arange(1, 10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [29]:
tensor.argmax()

tensor(2)

In [30]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [31]:
# reshape
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [32]:
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [33]:
# change views will change a tensor
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [34]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [36]:
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [37]:
# Numpy
array = np.arange(1, 10)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [38]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))